### ISSUE TITLE
Fair First-Come-First-Serve

### ISSUE THREAD

**Issue by lujobi** [amiv-eth/amivapi#352] opened 2019-02-23 12:45 UTC
As discussed: Fair First-Come-First-Serve would be great.

**Comment by NotSpecial** [comment] 2019-02-23 16:58
Which discussion are you referring to, can you provide more detail?

Fair-FCFS can be tackled in many different ways, are there any preferences and/or requirements?

**Comment by lujobi** [comment] 2019-02-23 17:55
Sure, as almost always when talking about Fair-FCFS the Skiweekend comes up. Since now we have the one-click-login it depends even more on the internet connection than before. 
My idea for the Fair FCFS would be, that everyone who enrolls within the first minute will land in a pot from which the spots and place on the waiting list are drawn randomly.

**Comment by NotSpecial** [comment] 2019-02-23 18:15
Thanks for your feedback.

How should the time delay be determined? Do you think an API-wide fixed value (easy) would be sufficient? Or do different events require different delays?

**Comment by lujobi** [comment] 2019-02-23 18:22
I think one (fixed) minute should work out fine. It should mainly accommodate the different (decent) internet connections.

**Comment by NotSpecial** [comment] 2019-02-23 18:24
Thanks for the feedback! That should be possible.

**Comment by temparus** [comment] 2019-03-11 10:48
This is a duplicate of #110.

**Closed** 2019-03-11 10:50 UTC
Labels: duplicate, enhancement
